export const getAllIndustries = [
  { value: 'An toàn lao động' },
  { value: 'Bán hàng kỹ thuật' },
  { value: 'Bán lẻ/ Bán sỉ' },
  { value: 'Báo chí/ Truyền hình' },
  { value: 'Bảo hiểm' },
  { value: 'Bảo trì/ Sửa chữa' },
  { value: 'Bất động sản' },
  { value: 'Biên/ Phiên dịch' },
  { value: 'Bưu chính - Viễn thông' },
  { value: 'Chứng khoán/ Vàng/ Ngoại tệ' },
  { value: 'Cơ khí/ Chế tạo/ Tự động hóa' },
  { value: 'Công nghệ cao' },
  { value: 'Công nghệ ô tô' },
  { value: 'Công nghệ thông tin' },
  { value: 'Dầu khí/ Hóa chất' },
  { value: 'Dệt may/ Da giày' },
  { value: 'Địa chất/ Khoáng sản' },
  { value: 'Dịch vụ nhà hàng' },
  { value: 'Điện/ Điện tử/ Điện lạnh' },
  { value: 'Điện tử viễn thông' },
  { value: 'Du lịch' },
  { value: 'Dược phẩm/ Công nghệ sinh học' },
  { value: 'Giáo dục/ Đào tạo' },
  { value: 'Hàng cao cấp' },
  { value: 'Hàng gia dụng' },
  { value: 'Hàng hải' },
  { value: 'Hàng không' },
  { value: 'Hàng tiêu dùng' },
  { value: 'Hành chính/ Văn phòng' },
  { value: 'Hóa học/ Sinh học' },
  { value: 'Hoạch định/ Dự án' },
  { value: 'In ấn/ Xuất bản' },
  { value: 'IT Phần cứng/ Mạng' },
  { value: 'IT Phần mềm' },
  { value: 'Kế toán/ Kiểm toán' },
  { value: 'Khách sạn/ Nhà hàng' },
  { value: 'Kiến trúc' },
  { value: 'Kinh doanh/ Bán hàng' },
  { value: 'Logistics' },
  { value: 'Luật/ Pháp lý' },
  { value: 'Marketing/ Truyền thông/ Quảng cáo' },
  { value: 'Môi trường/ Xử lý chất thải' },
  { value: 'Mỹ phẩm/ Trang sức' },
  { value: 'Mỹ thuật/ Mỹ nghệ/ Điện ảnh' },
  { value: 'Ngân hàng/ Tài chính' },
  { value: 'Phi chính phủ/ Phi lợi nhuận' },
  { value: 'Nhân sự' },
  { value: 'Nông/ Lâm/ Ngư nghiệp' },
  { value: 'Quản lý chất lượng (QA/ QC)' },
  { value: 'Quản lý điều hành' },
  { value: 'Sản phẩm công nghiệp' },
  { value: 'Sản xuất' },
  { value: 'Spa/ Làm đẹp' },
  { value: 'Tài chính/ Đầu tư' },
  { value: 'Thiết kế đồ họa' },
  { value: 'Thiết kế nội thất' },
  { value: 'Thời trang' },
  { value: 'Thư ký/ Trợ lý' },
  { value: 'Thực phẩm/ Đồ uống' },
  { value: 'Tổ chức sự kiện/ Quà tặng' },
  { value: 'Tư vấn' },
  { value: 'Vận tải/ Kho vận' },
  { value: 'Xây dựng' },
  { value: 'Xuất nhập khẩu' },
  { value: 'Y tế/ Dược' },
  { value: 'Các ngành nghề khác' }
]
export const getAllFiles = [
  { value: 'Agency (Design/ Development)' },
  { value: 'Agency (Marketing/ Advertising)' },
  { value: 'Bán lẻ - Hàng tiêu dùng - FMCG' },
  { value: 'Bảo hiểm' },
  { value: 'Bảo trì/ Sửa chữa' },
  { value: 'Bất động sản' },
  { value: 'Chứng khoán' },
  { value: 'Cơ khí' },
  { value: 'Cơ quan nhà nước' },
  { value: 'Du lịch' },
  { value: 'Dược phẩm/ Y tế/ Công nghệ sinh học' },
  { value: 'Điện tử/ Điện lạnh' },
  { value: 'Giải trí' },
  { value: 'Giáo dục/ Đào tạo' },
  { value: 'In ấn/ Xuất bản' },
  { value: 'Internet/ Online' },
  { value: 'IT - Phần cứng' },
  { value: 'IT - Phần mềm' },
  { value: 'Kế toán/ Kiểm toán' },
  { value: 'Logistics - Vận tải' },
  { value: 'Luật' },
  { value: 'Marketing/ Truyền thông/ Quảng cáo' },
  { value: 'Môi trường' },
  { value: 'Năng lượng' },
  { value: 'Ngân hàng' },
  { value: 'Nhà hàng/ Khách sạn' },
  { value: 'Nhân sự' },
  { value: 'Nông/ Lâm/ Ngư nghiệp' },
  { value: 'Sản xuất' },
  { value: 'Tài chính' },
  { value: 'Thiết kế/ Kiến trúc' },
  { value: 'Thời trang' },
  { value: 'Thương mại điện tử' },
  { value: 'Tổ chức phi lợi nhuận' },
  { value: 'Tự động hóa' },
  { value: 'Tư vấn' },
  { value: 'Viễn thông' },
  { value: 'Xây dựng' },
  { value: 'Xuất nhập khẩu' },
  { value: 'Khác' }
]
// export class Industries {
//   public static getAllIndustries = async () => {
//     const rs = await axios.get(`https://www.topcv.vn/categories/list-top`)
//     return rs.data.categories
//   }
// }

// export default Industries
